{% set name = "pyquokka" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marsupialtail/quokka/archive/v{{ version }}.tar.gz
  sha256: b6bbb20dab13a5c21ba1a1aa8484a2b9b0d0c67cfbfc1264e63ee5d8cdc2f731

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3
    - h5py
    - numpy
    - pandas
    - protobuf ==3.20.*
    - polars ==0.14.*
    - psutil
    - pyarrow
    - python >=3.6
    - python-graphviz
    - ray-core
    - redis-py
    - sqlglot

test:
  commands:
    - LD_DEBUG=libs python -c "import pyquokka"  # [linux]
    - python -c "import pyquokka"  # [not linux]
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marsupialtail/quokka
  doc_url: https://marsupialtail.github.io/quokka/
  license: Apache-2.0
  license_file: LICENSE
  summary: Open source SQL engine in Python.

extra:
  recipe-maintainers:
    - thewchan
