{% set name = "pyquokka" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marsupialtail/quokka/archive/v{{ version }}.tar.gz
  sha256: 67891ca83b1aa114c91ac417523fa1c1a4a42dc61eb21f212ecf5d59bd179bab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - boto3
    - botocore
    - cffi
    - numpy
    - pandas
    - protobuf
    - polars >=0.17.0
    - psutil
    - pyarrow
    - python >={{ python_min }}
    - python-duckdb >=0.6.0
    - python-graphviz
    - ray-core >=2.0.0
    - redis-py
    - sqlglot >=11.4.2
    - threadpoolctl
    - tqdm

test:
  commands:
    - LD_DEBUG=libs python -c "import pyquokka"  # [linux]
    - pip check
  requires:
    - pip
    - threadpoolctl
    - python {{ python_min }}

about:
  home: https://github.com/marsupialtail/quokka
  doc_url: https://marsupialtail.github.io/quokka/
  license: Apache-2.0
  license_file: LICENSE
  summary: Open source SQL engine in Python.

extra:
  recipe-maintainers:
    - thewchan
