{% set name = "pyquokka" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marsupialtail/quokka/archive/v{{ version }}.tar.gz
  sha256: 844210edcc460ec1f5863a680ecf8fcf8b83b880f145d9c34b90597f8e02e19e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - boto3
    - botocore
    - h5py
    - numpy
    - pandas
    - parallel-ssh
    - protobuf
    - polars >=0.16.8
    - psutil
    - pyarrow
    - python >=3.6
    - python-duckdb >=0.6.0
    - python-graphviz
    - ray-core >=2.0.0
    - redis-py
    - sqlglot
    - tqdm

test:
  commands:
    - LD_DEBUG=libs python -c "import pyquokka"  # [linux]
    - python -c "import pyquokka"  # [not linux]
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marsupialtail/quokka
  doc_url: https://marsupialtail.github.io/quokka/
  license: Apache-2.0
  license_file: LICENSE
  summary: Open source SQL engine in Python.

extra:
  recipe-maintainers:
    - thewchan
